// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOzoTVGHZXRI4-IoI4ruDEGtuWoyu8U8',
    appId: '1:224065817202:web:3a85421cfaf3f56e3bd0eb',
    messagingSenderId: '224065817202',
    projectId: 'uesb-eventos',
    authDomain: 'uesb-eventos.firebaseapp.com',
    storageBucket: 'uesb-eventos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJvYHJFFLsWTDY9mn_IXaP1yw0PVlzQ7Q',
    appId: '1:224065817202:android:4aa60f9a71353f4b3bd0eb',
    messagingSenderId: '224065817202',
    projectId: 'uesb-eventos',
    storageBucket: 'uesb-eventos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uchyXmCXGc3hblJEbMXKT1rNAMTcAlk',
    appId: '1:224065817202:ios:a0b1337c31fafb793bd0eb',
    messagingSenderId: '224065817202',
    projectId: 'uesb-eventos',
    storageBucket: 'uesb-eventos.appspot.com',
    iosClientId: '224065817202-e5rtvddavf3a2sqtmvs5b5qboi79k6ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.uesbEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uchyXmCXGc3hblJEbMXKT1rNAMTcAlk',
    appId: '1:224065817202:ios:a0b1337c31fafb793bd0eb',
    messagingSenderId: '224065817202',
    projectId: 'uesb-eventos',
    storageBucket: 'uesb-eventos.appspot.com',
    iosClientId: '224065817202-e5rtvddavf3a2sqtmvs5b5qboi79k6ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.uesbEventos',
  );
}
